db_connections:

    main:
        host: database
        port: 5432
        database: darwin
        user: darwin
        password: darwin

app:
    fcm_api_key: "AAAAndJ7bMY:APA91bFsdGo1pn4c_dh7RBkAQ_ROojyQkmrVytK3HzapUVtHCX4suBzG8kaNVO1RcKs0iGOhden_mpvpe7Nu9HpOLDuMxY9riSRzYa3JRiXtGXfTdoKRaRK7L7tNrvSCoBviwaAXNa75"



